name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite site
        run: npm run build
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Debug print VITE env
        run: |
          set +e
          echo "VITE_GOOGLE_MAPS_API_KEY: $VITE_GOOGLE_MAPS_API_KEY"
          env | grep VITE_GOOGLE_MAPS_API_KEY || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 你也可以改用 GH_PAT
          publish_branch: gh-pages
          publish_dir: ./dist
