name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js (for string replacement, not required for static hosting)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate const.js with secret
        run: |
          echo "const GOOGLE_MAPS_API_KEY = \"${{ secrets.GOOGLE_MAPS_API_KEY }}\";" > ./const.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: .
